FROM ubuntu:trusty
WORKDIR /var/lib/ejabberd
RUN apt-get update
RUN apt-get install -y gnupg2 wget apt-transport-https
RUN echo "deb https://apt.jabber.at trusty ejabberd" > /etc/apt/sources.list.d/jabber.at.list
RUN wget -qO- https://apt.jabber.at/gpg-key | apt-key add -
RUN apt-get update
RUN apt-get install -y ejabberd erlang-p1-sip
RUN mkdir -p /run/ejabberd
RUN chown ejabberd:ejabberd /run/ejabberd /var/lib/ejabberd
ADD files/15.07/ejabberdctl /usr/sbin/ejabberdctl

USER ejabberd
EXPOSE 5222 5269 5280
VOLUME ["/var/lib/ejabberd", "/etc/ejabberd", "/var/log/ejabberd"]
CMD ["/usr/sbin/ejabberdctl", "start"]
