FROM debian:jessie
WORKDIR /var/lib/ejabberd
RUN apt-get update
RUN apt-get install -y ejabberd erlang-p1-sip
RUN mkdir -p /run/ejabberd
RUN chown ejabberd:ejabberd /run/ejabberd /var/lib/ejabberd
ADD ejabberdctl-14.07 /usr/sbin/ejabberdctl

USER ejabberd
EXPOSE 5222 5269 5280
VOLUME ["/var/lib/ejabberd", "/etc/ejabberd", "/var/log/ejabberd"]
CMD ["/usr/sbin/ejabberdctl", "start"]
